# Remote Setting
baseurl: "/" #https://github.com/pmarsceill/just-the-docs/issues/148
#url: "imagelearning.community"
repository: pauliver/imagelearning.community

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs


