# Remote Setting
baseurl: "/" #https://github.com/pmarsceill/just-the-docs/issues/148
#url: "imagelearning.community"
repository: pauliver/imagelearning.community

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Image Learning":
    - "//github.com/ImageLearning/ImageLearning.Community/"

# Supports true (default) or false/nil
heading_anchors: true

footer_content: "Copyright &copy; 2019-2020 Paul Oliver. Distributed by an <a href=\"https://github.com/ImageLearning/ImageLearning.Community/blob/master/LICENSE\">MIT license.</a>"

color_scheme: "dark"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-159396166-2
