# Remote Setting
baseurl: "/" #https://github.com/pmarsceill/just-the-docs/issues/148
#url: "imagelearning.community"
repository: pauliver/imagelearning.community

title: Image Learning

description: A community for Machine Learning around Image Recognition

permalink: pretty

# Theme
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Image Learning":
    - "//github.com/ImageLearning/ImageLearning.Community/"

# Supports true (default) or false/nil
heading_anchors: true

footer_content: "Copyright &copy; 2019-2020 Paul Oliver. Distributed by an <a href=\"https://github.com/ImageLearning/ImageLearning.Community/blob/master/LICENSE\">MIT license.</a>"

color_scheme: "nil"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-3XQ0H5FKMP

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
